### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by danslapman** [IronCoreLabs/cats-scalatest#287]
Please, cross-compile this library against Scala 3 🙏

**Comment by coltfred** [comment]
Sorry this went unanswered so long. I lost track of it. We're currently still on 2.13 so I haven't taken the time to get this ported over. It goes without saying that I'd happily take a PR for it and since it's such an easy project it probably isn't much work.

If no one else takes it on I'll try to get to it in the next few weeks.

**Comment by coltfred** [comment]
4.0.0 was just published and should be making its way to maven central now.

LMK if something is amiss

**Comment by danslapman** [comment]
Thank You 👍
